Fixes #18909: Add an "upgrade only" option to the technique packageManagement
Normation/rudder-techniques pull request #1650
Opened 2021-02-16 15:50 UTC by Fdall

https://issues.rudder.io/issues/18909

2021-02-16 15:50 UTC, Fdall commented
this is just an initial commit for reference

2021-02-16 15:51 UTC, Fdall commented
PR updated with a new commit

2021-02-17 10:05 UTC, ncharles commented on techniques/applications/packageManagement/1.3/metadata.xml
> +          <LABEL>Only if already installed</LABEL>
"Upgrade only if already installed" or something like that ?

2021-02-17 10:22 UTC, ncharles commented on techniques/applications/packageManagement/1.3/packageManagement.st
> +      # Force t oaudit mode to verify if packages are already installed (whatever their version is)
this should be done only if "state_upgrade_only_${index_pkg}"

2021-02-17 10:29 UTC, ncharles commented on techniques/applications/packageManagement/1.3/packageManagement.st
> +  reports:
why the empty report ?

2021-02-17 14:32 UTC, Fdall commented
PR updated with a new commit

2021-03-01 14:54 UTC, ncharles requested changes
some minor comments.
I'll check the code as well

2021-03-01 14:54 UTC, ncharles commented on techniques/applications/packageManagement/1.3/packageManagement.st
> +      "remove_dry_run_mode"            usebundle => push_dry_run_mode("true");
shouldn't it be "force dry_run_mode" ? even if it's only a comment, it would help

2021-03-01 14:54 UTC, ncharles commented on techniques/applications/packageManagement/1.3/packageManagement.st
> +      "report_na_${index_pkg}" usebundle => rudder_common_report("packageManagement", "result_na", "${trackingkey[${index_pkg}]}", "Package", "${package[${index_pkg}]}", "Upgrade only set but the pac
```suggestion
      "report_na_${index_pkg}" usebundle => rudder_common_report_index("packageManagement", "result_na", "${trackingkey[${index_pkg}]}", "Package", "${package[${index_pkg}]}", "Upgrade only set for package ${package[${index_pkg}]} but this package was not found on the machine.", "${index_pkg}"),
```

2021-03-01 15:39 UTC, ncharles commented on techniques/applications/packageManagement/1.3/packageManagement.st
> +      "already_installed_${index_pkg}" usebundle => package_state_options("${package[${index_pkg}]}", "any", "${architecture[${index_pkg}]}", "${manager[${index_pkg}]}", "present", "${manager_final_o
if we have two different technique, one with upgrade only first and the second with install, it will skip the install part and fail

2021-03-01 15:51 UTC, ncharles commented on techniques/applications/packageManagement/1.3/packageManagement.st
> +      "package_${index_pkg}" usebundle => package_state_options("${package[${index_pkg}]}", "${version[${index_pkg}]}", "${architecture[${index_pkg}]}", "${manager[${index_pkg}]}", "${ncf_state[${ind
this is not correctly executed 
I have reports: 
`verbose: P:    From parameterized bundle: _log_v3( {"Presence of package tree in any version","htop","package_state_options_htop","package_state_options_htop_any_default_default_present_","@{args}"})
`

2021-03-01 15:55 UTC, VinceMacBuche commented on techniques/applications/packageManagement/1.3/changelog
> +  ** Convert to multiversionned technique
It misses a changelog entry, stating that Felix the great has done this version

2021-03-02 09:15 UTC, Fdall commented
PR updated with a new commit

2021-03-02 09:19 UTC, Fdall commented
PR updated with a new commit

2021-03-02 09:24 UTC, Fdall commented
PR updated with a new commit

2021-03-02 09:53 UTC, ncharles commented on techniques/applications/packageManagement/1.3/changelog
> + -- Félix Dallidet <felix.dallidet@rudder.io> Thu Mar 1 10:23:30 2021
```suggestion
 -- Félix Dallidet <felix.dallidet@rudder.io> Mon Mar 1 10:23:30 2021
```

2021-03-02 09:53 UTC, ncharles commented on techniques/applications/packageManagement/1.3/changelog
> +  * Version 1.2
```suggestion
  * Version 1.3
```

2021-03-02 10:37 UTC, Fdall commented
PR updated with a new commit

2021-03-02 11:02 UTC, ncharles approved these changes

2021-03-02 11:02 UTC, Normation-Quality-Assistant commented
This PR is not mergeable to upper versions.
Since it is "Ready for merge" you must merge it by yourself using the following command:
`rudder-dev merge https://github.com/Normation/rudder-techniques/pull/1650`
-- Your faithful QA
Kant merge: "Happiness is not an ideal of reason, but of imagination."
 (https://ci.normation.com/jenkins/job/merge-accepted-pr/36010/console)

2021-03-02 11:03 UTC, ncharles requested changes
it is missing the change of list of maintaine version

2021-03-02 14:51 UTC, Fdall commented
PR updated with a new commit

2021-03-02 15:29 UTC, ncharles approved these changes

2021-03-02 15:29 UTC, Normation-Quality-Assistant commented
This PR is not mergeable to upper versions.
Since it is "Ready for merge" you must merge it by yourself using the following command:
`rudder-dev merge https://github.com/Normation/rudder-techniques/pull/1650`
-- Your faithful QA
Kant merge: "All our knowledge begins with the senses, proceeds then to the understanding, and ends with reason. There is nothing higher than reason."
 (https://ci.normation.com/jenkins/job/merge-accepted-pr/36024/console)

2021-03-03 09:44 UTC, Fdall commented
OK, squash merging this PR

2021-03-03 09:45 UTC, merged