Fixes #19103: Add a Rudder postgres system technique
Normation/rudder-techniques pull request #1656
Opened 2021-03-31 13:48 UTC by Fdall

https://issues.rudder.io/issues/19103

2021-04-02 09:17 UTC, Fdall commented
PR updated with a new commit

2021-06-14 09:57 UTC, Fdall commented
PR updated with a new commit

2021-06-14 10:38 UTC, Fdall commented
PR updated with a new commit

2021-06-14 11:54 UTC, ncharles commented on techniques/system/rudderPostgresql/1.0/main.st
> +    sles_12_0|sles_12_1|sles_12_2::
i wish we could drop support for server SLES12SP2 and earlier

2021-06-14 11:54 UTC, ncharles commented on techniques/system/rudderPostgresql/1.0/main.st
> +    # sles 12, sp1 and sp2 don't have by default a systemd postgresql
this comment is missplaced

2021-06-14 11:54 UTC, ncharles commented on techniques/system/rudderPostgresql/1.0/main.st
> +    !(sles_12_0|sles_12_1|sles_12_2)::
where is the vars: ?

2021-06-14 11:55 UTC, ncharles requested changes
there seems to be copy and paste error in bundle common

2021-06-14 13:12 UTC, Fdall commented
PR updated with a new commit

2021-06-14 19:10 UTC, ncharles approved these changes

2021-06-14 19:10 UTC, Normation-Quality-Assistant commented
This PR is not mergeable to upper versions.
Since it is "Ready for merge" you must merge it by yourself using the following command:
`rudder-dev merge https://github.com/Normation/rudder-techniques/pull/1656`
-- Your faithful QA
Kant merge: "It is beyond a doubt that all our knowledge begins with experience."
 (https://ci.normation.com/jenkins/job/merge-accepted-pr/40316/console)

2021-06-15 07:54 UTC, Fdall commented
OK, squash merging this PR

2021-06-15 07:56 UTC, Fdall commented
OK, squash merging this PR

2021-06-15 08:00 UTC, Normation-Quality-Assistant commented
This PR is not mergeable to upper versions.
Since it is "Ready for merge" you must merge it by yourself using the following command:
`rudder-dev merge https://github.com/Normation/rudder-techniques/pull/1656`
-- Your faithful QA
Kant merge: "In law a man is guilty when he violates the rights of others. In ethics he is guilty if he only thinks of doing so."
 (https://ci.normation.com/jenkins/job/merge-accepted-pr/40345/console)

2021-06-15 08:00 UTC, Fdall commented
PR rebased

2021-06-15 08:05 UTC, Fdall commented
OK, squash merging this PR

2021-06-15 08:05 UTC, merged