Fixes #19037: Refactor the system techniques by component
Normation/rudder-techniques pull request #1659
Opened 2021-04-02 10:21 UTC by Fdall

https://issues.rudder.io/issues/19037

2021-06-21 21:06 UTC, Fdall commented
PR rebased

2021-06-21 21:10 UTC, Fdall commented
PR updated with a new commit

2021-06-21 21:12 UTC, Fdall commented
PR updated with a new commit

2021-06-22 09:11 UTC, Fdall commented
PR updated with a new commit

2021-06-24 10:41 UTC, Fdall commented
PR updated with a new commit

2021-06-24 10:42 UTC, Fdall commented
PR rebased

2021-06-24 10:43 UTC, Fdall commented
Commit modified

2021-06-24 10:44 UTC, Fdall commented on techniques/system/rudderWebapp/1.0/updateNcfHash.cf
> +# Update the ncf hash
Root server part of old distributePolicy

2021-06-24 10:45 UTC, Fdall commented on techniques/system/rudderRelay/1.0/relay/propagatePromises.cf
> +#
Relay (non-root) part of the old distributePolicy technique.

2021-06-24 10:46 UTC, Fdall commented on techniques/system/rudderRelay/1.0/relay/forwardInventory.cf
> +# Sending the inventory to the Rudder Server (or syncing with the server if we are a simple relay)
Relay (non-root) part of the old distributePolicy technique.

2021-06-24 10:46 UTC, Fdall commented on techniques/system/rudderRelay/1.0/metadata.xml
> -    <NAME>RUDDER_SERVER_ROLES</NAME>
now in serverRoles

2021-06-24 10:47 UTC, Fdall commented on techniques/system/rudderApache/1.0/apache/apache-certificate.cf
>  {
old name was apache_acl, but it did not manage apache ACLs at all.

2021-06-24 10:49 UTC, Fdall commented on systemTechniques.ldif
> +version: 1
This is a working file. It should not be put in this repository and is not exactly up to date.
But it is way easier for me to put it in the same PR than the technique changes.

2021-06-24 10:51 UTC, Fdall commented on techniques/system/rudderSlapd/1.0/main.st
> +      #"slapd_password"   string => "&RUDDER_LDAP_PASSWORD&";
We can not yet put dynamic informations such as LDAP password in the directive parameters in the current state of Rudder. So I fallback on the old way: parsing the rudder-passwords.conf

2021-06-24 10:53 UTC, Fdall commented on techniques/system/serverRoles/1.0/logrotate-check.st
> +      "logs_data"            data => parsejson('{
All the template logic has been moved from the template to the technique code. The resulting template is much more readable.
Still, this is mustache templating and may lead to empty fields if we do not test it properly

2021-06-24 10:54 UTC, Fdall commented on techniques/system/serverRoles/1.0/metadata.xml
> +<TECHNIQUE name="Server roles">
We should also move the services restart part from rudderApache here since it is a common feature to all server component.

2021-06-24 10:56 UTC, Fdall commented
Commit modified

2021-06-24 12:38 UTC, Fdall commented
Commit modified

2021-06-30 14:51 UTC, Fdall commented
PR updated with a new commit

2021-06-30 14:53 UTC, Fdall commented
PR updated with a new commit

2021-07-05 14:24 UTC, amousset commented
This needs a rebase

2021-07-08 12:25 UTC, Fdall commented
PR updated with a new commit

2021-07-08 12:27 UTC, Fdall commented
PR rebased

2021-07-08 12:29 UTC, Fdall commented
PR updated with a new commit

2021-07-08 12:45 UTC, Fdall commented
PR updated with a new commit

2021-07-08 12:50 UTC, Fdall commented
PR updated with a new commit

2021-07-08 12:51 UTC, Fdall commented
PR rebased

2021-07-12 13:10 UTC, Fdall commented
PR updated with a new commit

2021-07-12 14:11 UTC, Fdall commented
PR rebased

2021-07-12 14:38 UTC, Fdall commented on techniques/system/rudderApache/1.0/apache/system_rudder_apache_networks_configuration.cf
> +      "any" usebundle => permissions("${remote_run_file}", "600", "root", "0");
If the file does not exist, ensuring its permission is not really useful

2021-07-12 14:41 UTC, Fdall commented on techniques/system/rudderRelay/1.0/common/relayd.cf
> -  vars:
moved to rudderRelay/1.0/main.st

2021-07-12 14:42 UTC, Fdall commented on techniques/system/rudderRelay/1.0/metadata.xml
> -    <NAME>RUDDER_SERVER_ROLES</NAME>
Removed

2021-07-12 15:07 UTC, Fdall commented
PR updated with a new commit

2021-07-13 13:34 UTC, ncharles commented on techniques/system/rudderRelay/1.0/metadata.xml
> +    <!-- Note that the policy server is set via the common.xml -->
what is the common.xml ?

2021-07-13 13:36 UTC, Fdall commented on techniques/system/rudderRelay/1.0/metadata.xml
> +    <!-- Note that the policy server is set via the common.xml -->
No idea

2021-07-13 13:37 UTC, ncharles commented on techniques/system/rudderRelay/1.0/relay/propagatePromises.cf
> +bundle agent propagate_promises(trackingkey, technique_name, relay_sync_method, relayd_sync_promises, relay_sync_sharedfiles) {
```suggestion
bundle agent propagate_promises(trackingkey, technique_name, relay_sync_method, relay_sync_promises, relay_sync_sharedfiles) {
```

2021-07-13 13:44 UTC, ncharles requested changes
some files have licences header and some don't
it is not consistent

2021-07-13 13:48 UTC, ncharles approved these changes
licences are another PR
looks good to me

2021-07-13 17:00 UTC, Normation-Quality-Assistant commented
OK, squash merging this PR

2021-07-13 17:00 UTC, merged