Fixes #19121: Cleanup apache_acl bundle in the system technique DistributePolicy
Normation/rudder-techniques pull request #1660
Opened 2021-04-02 14:33 UTC by Fdall

https://issues.rudder.io/issues/19121

2021-04-12 09:48 UTC, ncharles requested changes
some minor changes

2021-04-12 09:48 UTC, ncharles commented on techniques/system/distributePolicy/1.0/apache-acl.cf
> +      "trackingkey   "     string => "${distribute_policy_common.directiveId}";
extra space in the " " here

2021-04-12 09:48 UTC, ncharles commented on techniques/system/distributePolicy/1.0/apache-acl.cf
> +      "destination_1"      string => "${g.rudder_var}/lib/ssl/${ssl_ca_file}";
i would love to have better naming that _1 and _2

2021-04-12 13:29 UTC, Fdall commented
PR updated with a new commit

2021-04-12 14:22 UTC, ncharles approved these changes

2021-04-12 14:53 UTC, Normation-Quality-Assistant commented
This PR is not mergeable to upper versions.
Since it is "Ready for merge" you must merge it by yourself using the following command:
`rudder-dev merge https://github.com/Normation/rudder-techniques/pull/1660`
-- Your faithful QA
Kant merge: "Happiness is not an ideal of reason, but of imagination."
 (https://ci.normation.com/jenkins/job/merge-accepted-pr/37582/console)

2021-04-30 08:17 UTC, Fdall commented
OK, squash merging this PR

2021-04-30 08:17 UTC, merged