Fixes #21858: Command seq not found in crontab on AIX
Normation/rudder-techniques pull request #1792
Opened 2022-09-26 15:52 UTC by ncharles

https://issues.rudder.io/issues/21858

2022-09-27 07:37 UTC, ncharles commented
PR updated with a new commit

2022-09-27 08:21 UTC, ncharles commented
PR updated with a new commit

2022-09-27 08:22 UTC, ncharles commented
PR updated with a new commit

2022-09-27 08:44 UTC, amousset approved these changes

2022-09-30 07:54 UTC, Normation-Quality-Assistant commented
This PR is not mergeable to upper versions.
Since it is "Ready for merge" you must merge it by yourself using the following command:
`rudder-dev merge https://github.com/Normation/rudder-techniques/pull/1792`
-- Your faithful QA
Kant merge: "All our knowledge begins with the senses, proceeds then to the understanding, and ends with reason. There is nothing higher than reason."
 (https://ci.normation.com/jenkins/job/merge-accepted-pr/60447/console)

2022-10-12 21:05 UTC, amousset requested changes
This does not work as expected

2022-10-12 22:01 UTC, amousset commented on techniques/system/common/1.0/cron-setup.cf
> +        edit_line => delete_lines_matching("sh: seq:.*# RUDDER CRON");
```suggestion
```

2022-10-12 22:02 UTC, amousset commented on techniques/system/common/1.0/cron-setup.cf
> +        edit_line => delete_lines_matching("sh: seq:.*# RUDDER CRON");
Replace 

```
edit_line     => insert_lines("${cron_prefix} /opt/rudder/bin/rudder agent check -q >> /var/log/rudder/agent-check/check.log 2>&1 # RUDDER CRON"),
```

by 

```
edit_line     => converge("# RUDDER CRON", "${cron_prefix} /opt/rudder/bin/rudder agent check -q >> /var/log/rudder/agent-check/check.log 2>&1 # RUDDER CRON"),
```

Maintains a clean file

2022-12-02 12:00 UTC, ncharles commented
PR updated with a new commit

2022-12-02 12:21 UTC, ncharles commented
PR updated with a new commit

2022-12-09 11:04 UTC, amousset approved these changes

2022-12-09 11:06 UTC, Normation-Quality-Assistant commented
OK, squash merging this PR

2022-12-09 11:06 UTC, merged