Fixes #24022: File content directive add 4 spaces at the beginning of the line
Normation/rudder-techniques pull request #1839
Opened 2024-01-16 15:25 UTC by ElaadF

https://issues.rudder.io/issues/24022

2024-01-16 15:41 UTC, ElaadF commented
Commit modified

2024-01-16 21:57 UTC, ncharles requested changes
you need exactly 0 spaces

2024-01-16 21:57 UTC, ncharles commented on techniques/fileDistribution/fileTemplate/1.0/fileTemplate.ps1.st
> + &FILE_TEMPLATE_RAW_TEMPLATE:{rawSource |
```suggestion
&FILE_TEMPLATE_RAW_TEMPLATE:{rawSource |
```

2024-01-17 09:13 UTC, ElaadF commented
Commit modified

2024-01-22 15:12 UTC, ncharles approved these changes

2024-01-22 15:14 UTC, merged